# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Poslání"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  parent = "Poslání"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Příběhy Úspěchu"
  parent = "Poslání"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Neúspěch a Učební Zkušenosti"
  parent = "Poslání"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "Události"
  weight = 20

[[main]]
  name = "Nadcházející Akce"
  parent = "Události"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Veřejné Skupiny"
  parent = "Události"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Publikace"
  weight = 30

[[main]]
  name = "Články"
  parent = "Publikace"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Knihy"
  parent = "Publikace"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Kurzy"
  weight = 40

[[main]]
  name = "Kurz Spojení"
  parent = "Kurzy"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Praxe Spojení"
  parent = "Kurzy"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Zdroje"
  weight = 50

[[main]]
  name = "Čtu"
  parent = "Zdroje"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Stránky"
  parent = "Zdroje"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Sitemap"
  parent = "Zdroje"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "Kontakt"
  weight = 60

[[main]]
  name = "Kontakní Forma"
  parent = "Kontakt"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Vnitřní Skupina"
  parent = "Kontakt"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Eventbrite"
  parent = "Kontakt"
  pageRef = "posts"
  weight = 30

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20
